### ISSUE TITLE
Remove or make recommended HTML 1 rule related to B and I elements

### ISSUE THREAD

**Issue by jongund** [opena11y/oaa-rules#103]
This rule seems a little dated as a violation.  It seems a little tick-tacky to me and I have had some complaints about its importance.

**Comment by inspector508** [comment]
<i> is commonly used as a vehicle for background sprites and the like, so the tag will continue to show up.  I see people using <i> without a text node, but that’s a different violation.

I’d go with recommended, with a result of “warning” maybe?

**Comment by jongund** [comment]
Change to recommended rule.  Review meta data related to use.

**Comment by nhoyt** [comment]
It seems to me that B and I, because they are so commonly used in other contexts (e.g. WSIWYG editors) and have been part of HTML for so long, they have taken on semantic meaning (as opposed to just indicating style) in the realm of content. Their semantics are weaker than STRONG and EM, but because they arguably have semantics, the rule could/should be changed to Recommended.

**Comment by jongund** [comment]
These are already recommended rules, so should we just delete them?

It seems that this rule is more of a distraction from other more important rules.

**Comment by jongund** [comment]
Resolved at OpenAjax meeting on February 16th to remove the current rule from both rulesets, since HTML5 is including the B and I elements, and they can have semantic information.   There was some discussion of a new rule that may address the semantics of inline styling.
